services:
  # backend:
  #   image: ghcr.io/bthzang/aqa-backend-nestjs/aqa-be:latest
  #   restart: always
  #   labels:
  #     logging: "promtail"
  #     logging_jobname: "containerlogs"
  #   env_file:
  #     - .env
  #   links:
  #     - db
  #   networks:
  #     - uitfa

  # redis:
  #   image: redis:7.2.5
  #   restart: always
  #   volumes:
  #     - redis:/var/lib/redis/data
  #   depends_on:
  #     - backend
  #   env_file:
  #     - .env
  #   networks:
  #     - uitfa

  # redis-insight:
  #   image: redislabs/redisinsight:2.50.0
  #   restart: always
  #   depends_on:
  #     - redis
  #   networks:
  #     - uitfa

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - uitfa

  model:
    image: bthzang/uitfa-model:latest
    restart: always
    ports:
      - 8000:8000
    networks:
      - uitfa

volumes:
  redis:
    driver: local
  db:
    driver: local

networks:
  uitfa:
    driver: bridge
